build-SlackSdkLambdaLayer:
	mkdir -p "$(ARTIFACTS_DIR)/nodejs"
	npm install --prefix "$(ARTIFACTS_DIR)/nodejs" @slack/web-api
	npm install --prefix "$(ARTIFACTS_DIR)/nodejs" @slack/events-api
	npm install --prefix "$(ARTIFACTS_DIR)/nodejs" @slack/interactive-messages
