AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  EnvironmentType:
    Type: String
    AllowedValues:
      - Staging
      - Production
  EnvironmentTypeAbbreviation:
    Type: String
    AllowedValues:
      - stag
      - prod

Resources:
  OomLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      # It's not well documented, but afaik when a log group is a target of an
      # EventBridge rule, it *must* be named `/aws/events/…`
      LogGroupName: !Sub /aws/events/${EnvironmentTypeAbbreviation}-oom-events
      RetentionInDays: 14
      Tags:
        - { Key: prx:meta:tagging-version, Value: "2021-04-07" }
        - { Key: prx:cloudformation:stack-name, Value: !Ref AWS::StackName }
        - { Key: prx:cloudformation:stack-id, Value: !Ref AWS::StackId }
        - { Key: prx:ops:environment, Value: !Ref EnvironmentType }
        - { Key: prx:dev:application, Value: DevOps }
  OomEventRule:
    Type: AWS::Events::Rule
    Properties:
      EventPattern:
          source: [aws.ecs]
          detail-type: [ECS Task State Change]
          detail:
            containers:
              lastStatus: [STOPPED]
              reason: [wildcard: "*OutOfMemoryError*"]
      State: ENABLED
      Tags:
        - { Key: prx:meta:tagging-version, Value: "2021-04-07" }
        - { Key: prx:cloudformation:stack-name, Value: !Ref AWS::StackName }
        - { Key: prx:cloudformation:stack-id, Value: !Ref AWS::StackId }
        - { Key: prx:ops:environment, Value: !Ref EnvironmentType }
        - { Key: prx:dev:application, Value: DevOps }
      Targets:
        - Arn: !GetAtt OomLogGroup.Arn
          Id: !Sub ${EnvironmentTypeAbbreviation}-web-task-oom
  OomEventMetricFilter:
    Type: AWS::Logs::MetricFilter
    Properties:
      FilterPattern: ""
      LogGroupName: !Ref OomLogGroup
      MetricTransformations:
        - MetricName: !Sub OomTasksKilled${EnvironmentTypeAbbreviation}
          MetricNamespace: PRX/DevOps
          MetricValue: "1"
  OomAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ERROR [ECS] Task <${EnvironmentTypeAbbreviation}> TASK OUT OF MEMORY
      AlarmDescription: !Sub >-
        A ${EnvironmentType} ECS task was killed due to being out of memory.
        The logs will have information about the relevant container and task.
      ComparisonOperator: GreaterThanOrEqualToThreshold
      EvaluationPeriods: 1
      MetricName: !Sub OomTasksKilled${EnvironmentTypeAbbreviation}
      Namespace: PRX/DevOps
      Period: 60
      Statistic: SampleCount
      Tags:
        - { Key: prx:meta:tagging-version, Value: "2021-04-07" }
        - { Key: prx:cloudformation:stack-name, Value: !Ref AWS::StackName }
        - { Key: prx:cloudformation:stack-id, Value: !Ref AWS::StackId }
        - { Key: prx:ops:environment, Value: !Ref EnvironmentType }
        - { Key: prx:ops:cloudwatch-log-group-name, Value: !Ref OomLogGroup }
        - { Key: prx:dev:application, Value: DevOps }
      Threshold: 1
      TreatMissingData: notBreaching
